# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'FoodieFinder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodieFinder

  pod 'SwiftLint'

  target 'FoodieFinderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodieFinderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
